<<<<<<< HEAD
# Generated by Django 4.2 on 2023-08-03 12:09
=======
# Generated by Django 3.2.13 on 2023-04-30 15:53
>>>>>>> origin/master

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('name', models.CharField(max_length=128, unique=True, verbose_name='Название категории товаров')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание категории')),
=======
                ('name', models.CharField(max_length=128, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
>>>>>>> origin/master
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
<<<<<<< HEAD
                ('description', models.TextField(verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Цена товара')),
                ('quantity', models.PositiveBigIntegerField(default=0, verbose_name='Количество товара')),
                ('image', models.ImageField(upload_to='products_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='products.productcategory')),
=======
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('quantity', models.PositiveBigIntegerField(default=0)),
                ('image', models.ImageField(upload_to='products_images')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.productcategory')),
>>>>>>> origin/master
            ],
        ),
    ]
